# model path
policy_path: "{LEGGED_GYM_ROOT_DIR}/pre_train/g1/policy.pt"
# policy_path: "{LEGGED_GYM_ROOT_DIR}/pre_train/g1/policy_15000.pt"

# xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/g1/scene53.xml"
# xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/ShowCase/Scene_ShowCase.xml"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/g1_29dof/Scene_ShowCase.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [
  100, 100, 100, 150, 40, 40,        # 0-5  左腿
  100, 100, 100, 150, 40, 40,        # 6-11 右腿
  300, 300, 300,                     # 12-14 腰
  200, 200, 200, 100, 20, 20, 20,    # 15-21 左臂
  10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0,   # 22-28 左手（3指，一共7个关节）
  200, 200, 200, 100, 20, 20, 20,    # 29-35 右臂
  10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0,   # 36-42 右手
]

# 关节速度
kds: [
  2, 2, 2, 4, 2, 2,                  # 0-5  左腿
  2, 2, 2, 4, 2, 2,                  # 6-11 右腿
  5, 5, 5,                            # 12-14 腰
  4, 4, 4, 4, 1, 0.5, 0.5,           # 15-21 左臂
  2, 2, 2, 2, 2, 2, 2,               # 22-28 左手
  4, 4, 4, 4, 1, 0.5, 0.5,           # 29-35 右臂
  2, 2, 2, 2, 2, 2, 2,               # 36-42 右手
]

# 为后17个关节设置稳定的默认姿态
default_angles: [
  -0.1,  0.0,  0.0,  0.3, -0.2, 0.0,    # 0-5  左腿
  -0.1,  0.0,  0.0,  0.3, -0.2, 0.0,    # 6-11 右腿
   0.0,  0.0,  0.0,                     # 12-14 腰
   0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.0,   # 15-21 左臂
   0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.0,   # 22-28 左手
   0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.0,   # 29-35 右臂
   0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 0.0,   # 36-42 右手
]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 456

cmd_init: [0, 0, 0]

height_cmd: 0.74
min_height: 0.30
max_squat_depth: 0.3

obs_history_len: 6